### ISSUE TITLE
Is it convenient to share the source code?Thank you！！

### ISSUE THREAD

**Issue by PYMAQ** [zcgzcgzcg1/MediaSum#1]
Is it convenient to share the source code?Thank you！！
thanks！！！！

**Comment by zcgzcgzcg1** [comment]
We use the standard opensource version of pointer-generator summarization (https://github.com/abisee/pointer-generator), BART-Large (https://huggingface.co/transformers/model_doc/bart.html) and UniLM-base-uncased (https://github.com/microsoft/unilm).
