### ISSUE TITLE
Predictions Order

### ISSUE THREAD

**Issue by Hannibal046** [zcgzcgzcg1/MediaSum#5]
Hello,
could you please tell in which order the predictions are generated?

according to `train_val_test_split.json`,the first prediction id should be `CNN-45061` whose summary is
 `Report Out of Afghanistan that Taliban Supreme Leader Getting Ready to Hand Over Kandahar; Discussion with Brother of Special Forces Soldier Killed in Afghanistan`, 

but the first predictions you gave of BartModel is:
 `the summer job market is shaping up to be the weakest in more than 50 years. so how do you get your teenage kids not to spend the entire summer glued to the couch? day to day personal finance contributor michelle singletary offers some tips.
on the designated day, dozens of eighth graders wore big curly wigs and chambray shirts. then they painted along to an episode of ross' pbs show the joy of painting.`

**Comment by zcgzcgzcg1** [comment]
Good catch. Our code uses the order of the input data in the news_dialogue.zip, starting from NPR and then CNN, each with increasing integer id.

We just updated the train_val_test_split.json which reorders the test part to make the order match predictions.
